<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" retried="1" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="TESTS" duration-ms="27844" started-at="2020-10-13T13:22:43 CEST" finished-at="2020-10-13T13:23:11 CEST">
    <groups>
    </groups>
    <test name="Tests.UsuniecieGrupy" duration-ms="27844" started-at="2020-10-13T13:22:43 CEST" finished-at="2020-10-13T13:23:11 CEST">
      <class name="Tests.UsuniecieGrupy">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Tests.UsuniecieGrupy@68759011]" name="beforeTest" is-config="true" duration-ms="4989" started-at="2020-10-13T13:22:43 CEST" finished-at="2020-10-13T13:22:48 CEST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Tests.UsuniecieGrupy@68759011]" name="afterTest" is-config="true" duration-ms="105" started-at="2020-10-13T13:22:54 CEST" finished-at="2020-10-13T13:22:54 CEST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Tests.UsuniecieGrupy@68759011]" name="beforeTest" is-config="true" duration-ms="3898" started-at="2020-10-13T13:22:54 CEST" finished-at="2020-10-13T13:22:58 CEST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="SKIP" signature="test()[pri:0, instance:Tests.UsuniecieGrupy@68759011]" name="test" duration-ms="4388" retried="true" started-at="2020-10-13T13:22:58 CEST" description="as Admin Try Add New Certificate" finished-at="2020-10-13T13:23:03 CEST">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Nie ma takiej grupy]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Nie ma takiej grupy
at PageObject.GroupPage.clickOnDeleteGroupButton(GroupPage.java:134)
at Tests.UsuniecieGrupy.test(UsuniecieGrupy.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:204)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Tests.UsuniecieGrupy@68759011]" name="afterTest" is-config="true" duration-ms="143" started-at="2020-10-13T13:23:03 CEST" finished-at="2020-10-13T13:23:03 CEST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Tests.UsuniecieGrupy@68759011]" name="beforeTest" is-config="true" duration-ms="4020" started-at="2020-10-13T13:23:03 CEST" finished-at="2020-10-13T13:23:07 CEST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="test()[pri:0, instance:Tests.UsuniecieGrupy@68759011]" name="test" duration-ms="4166" started-at="2020-10-13T13:23:07 CEST" description="as Admin Try Add New Certificate" finished-at="2020-10-13T13:23:11 CEST">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Nie ma takiej grupy]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Nie ma takiej grupy
at PageObject.GroupPage.clickOnDeleteGroupButton(GroupPage.java:134)
at Tests.UsuniecieGrupy.test(UsuniecieGrupy.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:204)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Tests.UsuniecieGrupy@68759011]" name="afterTest" is-config="true" duration-ms="141" started-at="2020-10-13T13:23:11 CEST" finished-at="2020-10-13T13:23:11 CEST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- Tests.UsuniecieGrupy -->
    </test> <!-- Tests.UsuniecieGrupy -->
  </suite> <!-- TESTS -->
</testng-results>
